version: "3.9"
services:
  db:
    container_name: pg_container
    image: postgres:15
    restart: always
    env_file:
      - .env-prod
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env-prod
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: audio_convert_app
    ports:
      - "8888:8000"
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data: